### ISSUE TITLE
Debug messages from status-go fleets not being relayed

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-status-legacy#11]
@iurimatias has reported not being able to receive messages from `eth.*` fleets on `status.prod` fleet. Possibly a bridge issue.

**Comment by jakubgs** [comment]
The `waku_node_messages_total` metric shows that something is being relayed:

![image](https://user-images.githubusercontent.com/2212681/175302295-c6ab6ddd-4f1b-4429-8182-f7ed2e979e97.png)

About 400 messages per 10 minutes, which is surprisingly regular, but it does match messages seen by `status.prod` fleet:

![image](https://user-images.githubusercontent.com/2212681/175302419-44c87e8a-9af4-4549-b43a-9c827033ccad.png)

Almost too perfectly.

**Comment by jakubgs** [comment]
The only thing that looks kinda weird in metrics are these `conn_init_failures` errors:

https://media.discordapp.net/attachments/950783419112095764/989511387350970408/unknown.png?width=1621&height=373

Not sure what that means though. @jm-clius ideas?

**Comment by jakubgs** [comment]
All peers metrics on the bridge hosts show zero:
```
admin@bridge-01.do-ams3.status.prod:~ % c 0:8008/metrics | grep -E '^[a-z_]+peers '
connected_peers 0.0
waku_store_peers 0.0
waku_filter_peers 0.0
waku_lightpush_peers 0.0
```
But that might just be showing unused metrics.

**Comment by jakubgs** [comment]
Envelopes dropped is a flat-line for last two days, but did have a spike 4 days ago:

![image](https://user-images.githubusercontent.com/2212681/175303113-ed42a450-c68a-48b1-92be-e4242090ac5b.png)

Lots of duplicates and and benign duplicates.

**Comment by jakubgs** [comment]
There was a spike in `waku_bridge_dropped_total` in the morning, but not right now:

![image](https://user-images.githubusercontent.com/2212681/175303416-218a4485-bdfc-4ffd-876f-3f257626d2db.png)

**Comment by jakubgs** [comment]
I restarted the bridge container to see what happens:
```
admin@bridge-01.do-ams3.status.prod:~ % d
CONTAINER ID   NAMES             IMAGE                                    CREATED      STATUS
f9278806e7c2   nim-waku-bridge   statusteam/nim-waku:deploy-bridge-prod   3 days ago   Up About a minute
```
Also re-connected peers.

**Comment by jakubgs** [comment]
Well, restarting definitely helped fix one metric:
```
admin@bridge-01.do-ams3.status.prod:~ % c 0:8008/metrics | grep -E '^[a-z_]+peers '
connected_peers 24.0
waku_store_peers 0.0
waku_filter_peers 0.0
waku_lightpush_peers 0.0
```
Before `connected_peers` was showing 0: https://github.com/status-im/infra-status/issues/11#issuecomment-1164369814

**Comment by jm-clius** [comment]
Already reported here https://github.com/status-im/nwaku/issues/1013 Working on a fix that will replenish connections to v1 periodically.

**Comment by jakubgs** [comment]
This graph shows very nicely how dropping of v1 messages goes down after restart on noon of 20st of June:

![image](https://user-images.githubusercontent.com/2212681/175322068-cacea07e-42a7-4132-bdd1-ee325a6680fe.png)

While v1 to v2 relay works until it just stops:

![image](https://user-images.githubusercontent.com/2212681/175322433-6b5d302f-26e0-438d-9e2b-5b8ce704774b.png)

My understanding is that as we have less and less v1 peers connected we see less and less v1 messages duplicates.

**Comment by jm-clius** [comment]
Possible fix: https://github.com/status-im/nwaku/pull/1020

**Comment by jakubgs** [comment]
No longer relevant.
