### ISSUE TITLE
Weird spikes in envelops and traffic on prod

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-status-legacy#12]
It was reported by desktop team that some nodes were returning errors like:
```
active mailserver changed   file=service.nim:104 node=/dns4/node-02.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg
history request started     file=service.nim:119 requestId=732abb44-de26-47e3-ae41-fab999b85708 numBatches=6
history request failed      file=service.nim:131 requestId=732abb44-de26-47e3-ae41-fab999b85708 errorMessage="stream reset"
mailserver not working      file=service.nim:114
```
This issue was first reported for `node-01.gc-us-central1-a.status.prod` where high CPU and traffic was discovered:

![image](https://user-images.githubusercontent.com/2212681/176273846-c7be5dc3-44e3-465b-a0ad-c87516218c12.png)

![image](https://user-images.githubusercontent.com/2212681/176273881-73f21ce1-d081-4301-ba68-3c2afbaabd8b.png)

https://grafana.infra.status.im/d/QCTZ8-Vmk/single-host-dashboard?orgId=1&var-host=node-01.gc-us-central1-a.status.prod&from=1656443054953&to=1656446654953

**Comment by jakubgs** [comment]
The fleet logs showed big spikes in numbers of messags:

![image](https://user-images.githubusercontent.com/2212681/176274020-9b2e3645-1c32-4bfc-a17b-584305562574.png)

As well as content topics:

![image](https://user-images.githubusercontent.com/2212681/176274048-5cc0b151-fba6-44cc-aea6-1c6bda7fc695.png)

https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&from=1656443034733&to=1656446634733&var-host=.*&var-fleet=status.prod&var-dc=All

**Comment by jakubgs** [comment]
While at the same time showing less peers(recovery probably due to `waku-peers` timer):

![image](https://user-images.githubusercontent.com/2212681/176274189-18a353a3-487a-478f-b478-baebccfd4fa5.png)

And less libp2p open streams:

![image](https://user-images.githubusercontent.com/2212681/176274131-8a435aab-f417-40f4-ac55-e8bd693f66de.png)

But elevated CPU usage on the whole fleet:

![image](https://user-images.githubusercontent.com/2212681/176274257-a37c0d16-0097-49bd-ae05-1ad06bf276f7.png)

**Comment by jakubgs** [comment]
Bridge v1 to v2 messages looked fine:

![image](https://user-images.githubusercontent.com/2212681/176274474-70c17576-e585-4ce3-841b-abb61c520141.png)

But v2 to v1 have a spike:

![image](https://user-images.githubusercontent.com/2212681/176274508-c505a001-3245-4647-8cfd-e72348c70ecf.png)

**Comment by jakubgs** [comment]
Store queries are quite low:

![image](https://user-images.githubusercontent.com/2212681/176274972-b60697f9-300c-4cd5-909b-99d1cb4ee288.png)

But waku store errors are ridiculous:

![image](https://user-images.githubusercontent.com/2212681/176275021-d010b36e-7ba4-40f5-a3fd-e307e7781d49.png)

I don't get it.

**Comment by jakubgs** [comment]
Issue coincides with 100% disk usage on the hosts:

![image](https://user-images.githubusercontent.com/2212681/176275186-8ee7ab78-02b7-44bf-b636-a154293577cc.png)

![image](https://user-images.githubusercontent.com/2212681/176275294-003324be-662b-42b3-a846-5a7e0afd666e.png)

**Comment by jakubgs** [comment]
Both store metrics weren't using `increase()`. This is a better view:

![image](https://user-images.githubusercontent.com/2212681/176276344-2c060fbf-6b18-4f8c-9481-043690f89bce.png)

![image](https://user-images.githubusercontent.com/2212681/176276223-1cd8f267-3051-4ae9-8436-6ddd9f69704c.png)

**Comment by jakubgs** [comment]
There is a matching jump in container memory usage:

![image](https://user-images.githubusercontent.com/2212681/176276938-5b9fe298-b2c3-4337-a24e-4ea85f0b74c1.png)

**Comment by jakubgs** [comment]
For now deploying this with some SQLite fixes: https://github.com/status-im/nwaku/commit/a2749c4a52c2013e02d2d10ef1d9eddd57b31d8d
https://ci.status.im/job/nim-waku/job/deploy-status-prod/9/console

**Comment by jm-clius** [comment]
Fix for issue related to store query performance: https://github.com/status-im/nwaku/issues/1024

**Comment by jakubgs** [comment]
No longer relevant:

![image](https://user-images.githubusercontent.com/2212681/229515046-daf8787e-90c0-4c85-a95d-cf705466858d.png)
