### ISSUE TITLE
Use DNS Discovery on test and prod fleet

### ISSUE THREAD

**Issue by fryorcraken** [status-im/infra-status-legacy#15]
test and prod fleets should use DNS Discovery, enrtree to be used should contains nodes of their own fleets (point to themselves).

**Comment by jm-clius** [comment]
Blocked by https://github.com/status-im/nwaku/pull/1128

**Comment by jm-clius** [comment]
Waiting for https://github.com/status-im/infra-role-go-waku/pull/2 and https://github.com/status-im/infra-go-waku/pull/5 so that the deployed, discoverable Merkle tree for each fleet contains both go-waku and nwaku nodes.

**Comment by jm-clius** [comment]
Now waiting for https://github.com/status-im/infra-status/issues/17 as final step.

**Comment by jm-clius** [comment]
This has been done. Lingering issue.
