### ISSUE TITLE
Increase store node retention to 30 days

### ISSUE THREAD

**Issue by felicio** [status-im/infra-status-legacy#19]
## What

- "modify storage setup on the nodes" (see https://github.com/status-im/infra-status/pull/18#issuecomment-1245909646)
- apply the change from https://github.com/status-im/infra-status/pull/18/files
- "deploys Ansible changes to fleets"

## Why

> The status products are built around a number of time based message availability assumptions (a legacy of the waku v1 30 day message persistence guarantee). As we move to waku v2, it is vitally important that waku v2 store nodes have the ability to offer the same time based guarantees that waku v1 mailserver nodes offered.
> 
> – https://docs.google.com/document/d/1it9_HTzOTvumBsUoeY3SEVFTJA-sSYrW89-HsEjriEg/edit?usp=sharing

**Comment by felicio** [comment]
See https://github.com/status-im/infra-status/pull/18#issuecomment-1246426515.

**Comment by jm-clius** [comment]
For now, we have decided to increase the retention to 30 days on _only_ the `status.prod` fleets as a start. This requires a dedicated data volume on those hosts as first step. cc @jakubgs

**Comment by jakubgs** [comment]
I've added an extra volume and increased retention on prod:

- https://github.com/status-im/infra-status/commit/6e1c4d7e - add 40 GB extra data volume for 30 days of history
- https://github.com/status-im/infra-status/commit/2c758246 - status: set 30 days of retention for prod fleet

Looks good:
```
 > a status -o -a 'df -h /docker | tail -n1'
node-02.do-ams3.status.prod | CHANGED | rc=0 | (stdout) /dev/sda         40G  2.6G   35G   7% /docker
node-01.do-ams3.status.prod | CHANGED | rc=0 | (stdout) /dev/sda         40G  2.6G   35G   7% /docker
node-01.gc-us-central1-a.status.prod | CHANGED | rc=0 | (stdout) /dev/sdb         40G  2.5G   35G   7% /docker
node-02.gc-us-central1-a.status.prod | CHANGED | rc=0 | (stdout) /dev/sdb         40G  2.5G   35G   7% /docker
node-02.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 | (stdout) /dev/vdb         40G  2.4G   35G   7% /docker
node-01.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 | (stdout) /dev/vdb         40G  2.4G   35G   7% /docker

 > a status -o -a 'grep retention /docker/nim-waku/docker-compose.yml'
node-02.do-ams3.status.prod | CHANGED | rc=0 | (stdout)       --sqlite-retention-time=2592000
node-01.do-ams3.status.prod | CHANGED | rc=0 | (stdout)       --sqlite-retention-time=2592000
node-01.gc-us-central1-a.status.prod | CHANGED | rc=0 | (stdout)       --sqlite-retention-time=2592000
node-02.gc-us-central1-a.status.prod | CHANGED | rc=0 | (stdout)       --sqlite-retention-time=2592000
node-01.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 | (stdout)       --sqlite-retention-time=2592000
node-02.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 | (stdout)       --sqlite-retention-time=2592000
```
