### ISSUE TITLE
update new waku v2 fleets to latest nim-waku

### ISSUE THREAD

**Issue by iurimatias** [status-im/infra-status-legacy#2]
the fleet needs to be updated to the latest commit https://github.com/status-im/nim-waku/commit/c27086e1865ce42ba1b318ceef634ace6b0f07f1

**Comment by jakubgs** [comment]
You know you can just do that yourself right?

* https://ci.status.im/job/nim-waku/job/deploy-v2-test/
* https://ci.status.im/job/nim-waku/job/deploy-v2-prod/

**Comment by iurimatias** [comment]
reopening due to this issue referring to the new wakuv2 test fleet. transferring the ticket to infra-status.

**Comment by jakubgs** [comment]
Indeed, the `infra-nim-waku` repo is resposible for `wakuv2.*` and `wakuv1.*` fleets.

This new repo is the home for `status.*` fleets.

**Comment by jakubgs** [comment]
Here's the CI build: https://ci.status.im/job/nim-waku/job/deploy-status-test/

And the repo change to use the new Docker image tag: https://github.com/status-im/infra-status/commit/50e58cd4

Done:
```
 > a all --become-user=admin -a 'docker ps'                                        
node-01.do-ams3.status.test | CHANGED | rc=0 >>
CONTAINER ID   NAMES      IMAGE                                    CREATED         STATUS
b5a0decbfa37   nim-waku   statusteam/nim-waku:deploy-status-test   6 minutes ago   Up 6 minutes (healthy)
node-01.gc-us-central1-a.status.test | CHANGED | rc=0 >>
CONTAINER ID   NAMES      IMAGE                                    CREATED         STATUS
e005df20c1f7   nim-waku   statusteam/nim-waku:deploy-status-test   6 minutes ago   Up 6 minutes (healthy)
node-01.ac-cn-hongkong-c.status.test | CHANGED | rc=0 >>
CONTAINER ID   NAMES      IMAGE                                    CREATED         STATUS
bb3ddd089224   nim-waku   statusteam/nim-waku:deploy-status-test   6 minutes ago   Up 6 minutes (healthy)
```
