### ISSUE TITLE
Add new flags to status.test: protected topics feature

### ISSUE THREAD

**Issue by alrevuelta** [status-im/infra-status-legacy#25]
@jakubgs Would like to introduce the following changes to `status.test`:
* Subscribe to a new topic
* Add a new flag with a given value

The new topic is:
`/waku/2/status-signed-test-1` which can be added with `--topics="/waku/2/status-signed-test-1 ...other-configured-topics"`

The new flag is:
`--protected-topic=/waku/2/status-signed-test-1:04070335f90e017ec1d7cb9a8e53d084dcf2c937cccb4272ed902881641613c6e0d46cf5531eee7ff8076616a2b8ac3436f71568f7a7032478fba3cac04c90e4e6`

This will "protect" said topic, so that only messages signed with the private key of that public key (see 04070335f...) will be routed in that topic.

Thanks!

**Comment by jakubgs** [comment]
Opened an issue about inconsistent flag usage for topics:

* https://github.com/waku-org/nwaku/issues/1726

**Comment by jakubgs** [comment]
Change:

- https://github.com/status-im/infra-role-nim-waku/commit/a0802a11 - docker: add support for --protected-topic flag
- https://github.com/status-im/infra-status/commit/a5b90f1f - status: add protected topic for test fleet

Result:
```
 > a status -a 'grep topic /docker/nim-waku/docker-compose.yml'   
node-01.do-ams3.status.test | CHANGED | rc=0 >>
      --topics='/waku/2/default-waku/proto /waku/2/status-signed-test-1'
      --protected-topic='/waku/2/status-signed-test-1:04070335f90e017ec1d7cb9a8e53d084dcf2c937cccb4272ed902881641613c6e0d46cf5531eee7ff8076616a2b8ac3436f71568f7a7032478fba3cac04c90e4e6'
node-01.gc-us-central1-a.status.test | CHANGED | rc=0 >>
      --topics='/waku/2/default-waku/proto /waku/2/status-signed-test-1'
      --protected-topic='/waku/2/status-signed-test-1:04070335f90e017ec1d7cb9a8e53d084dcf2c937cccb4272ed902881641613c6e0d46cf5531eee7ff8076616a2b8ac3436f71568f7a7032478fba3cac04c90e4e6'
node-01.ac-cn-hongkong-c.status.test | CHANGED | rc=0 >>
      --topics='/waku/2/default-waku/proto /waku/2/status-signed-test-1'
      --protected-topic='/waku/2/status-signed-test-1:04070335f90e017ec1d7cb9a8e53d084dcf2c937cccb4272ed902881641613c6e0d46cf5531eee7ff8076616a2b8ac3436f71568f7a7032478fba3cac04c90e4e6'
```
