### ISSUE TITLE
Debug message reliability issues with v0.20.0

### ISSUE THREAD

**Issue by richard-ramos** [status-im/infra-status-legacy#31]
During today's message reliability call, it was reported that messages are taking a lot of time to arrive to their intended recipients. Also, @siphiuel has reported some strange behaviour with filter nodes not responding to Filter Ping requests.
Looking at the nodes logs in kibana it's not clear to me these issues in status.prod fleet, here are some interesting graphs:
- Memory usage for ams nodes seem to have increased
![image](https://github.com/status-im/infra-status/assets/1106587/177a78a5-983b-4a31-846c-f4d2814fa91f)
- Same for the keepalive errors:
![image](https://github.com/status-im/infra-status/assets/1106587/829142b7-5e7e-428a-ba15-d1772d188430)
- Peerstore sizes, which quickly have reached the limit of 1K for those two nodes
![image](https://github.com/status-im/infra-status/assets/1106587/097fe714-fde1-4c90-ba8b-295f3d6de4ac)
These failure seems to match with the upgrade from 0.17 to 0.20 happening on 09/21
![image](https://github.com/status-im/infra-status/assets/1106587/297f048d-ab22-45c6-8cc9-8bb5413038ab)
cc: @cammellos @fryorcraken @iurimatias @jakubgs @jm-clius @John-44 @churik 

Maybe we should downgrade to v0.17?

**Comment by jakubgs** [comment]
If we look at fleet memory usage I can't see a clear memory increase that's significant:

![image](https://github.com/status-im/infra-status/assets/2212681/75bfc5c0-4431-48f4-9c8a-af22ceda47b9)

**Comment by jakubgs** [comment]
If we take `node-01.do-ams3.status.prod` as an example we can see some increase in memory usage:

![image](https://github.com/status-im/infra-status/assets/2212681/e5cdcbe8-96db-4884-b617-66db8aab5211)

And some increase in SWAP usage, but not a big one:

![image](https://github.com/status-im/infra-status/assets/2212681/06d94739-f253-4c8f-aec5-48e7b6f9e8e3)

**Comment by jakubgs** [comment]
What's interesting is we don't really see more I/O but less:

![image](https://github.com/status-im/infra-status/assets/2212681/a15beaf7-ac1b-418f-8e20-e57cfc50b689)

Same goes for number of I/O operations:

![image](https://github.com/status-im/infra-status/assets/2212681/ce4a9337-be9c-446b-be7d-093118e4be69)

And I/O wait is unchanged, flat mostly:

![image](https://github.com/status-im/infra-status/assets/2212681/0bd70e0f-f319-4730-ad04-0a6beb686216)

**Comment by jakubgs** [comment]
We could try downgrading, but to what version?
Also, would you say it makes sense to try to downgrade some of the fleet and compare?

**Comment by jakubgs** [comment]
This graph shows well that memory usage didn't change that much, but swap usage did:

![image](https://github.com/status-im/infra-status/assets/2212681/a6cdfb85-aabd-4c33-976d-93232c3a97b9)

**Comment by jakubgs** [comment]
The peer store size jump is the most clear change:

![image](https://github.com/status-im/infra-status/assets/2212681/0ccb6864-9af7-4117-b238-ef0624d1fc3f)

**Comment by jakubgs** [comment]
But what's interesting to me is this change in pattern of how messages are archived:

![image](https://github.com/status-im/infra-status/assets/2212681/11172a10-060f-4a30-b9d7-f19717f537ed)

Seems like it's done in bigger steps. What do you think @richard-ramos ?

**Comment by jakubgs** [comment]
It's weird how `do-ams3` hosts just flatlined in this graph:

![image](https://github.com/status-im/infra-status/assets/2212681/8812244a-358e-4f8c-94a1-4ea314799a5f)

Is this just a glitch in how we count archived messages or an actual storage issues?

**Comment by jakubgs** [comment]
While `ac-cn-hongkong-c` hosts start doing these steps:

![image](https://github.com/status-im/infra-status/assets/2212681/e5426eb2-e183-4939-b7ab-c01a47f17f4c)

**Comment by jakubgs** [comment]
We certainly seem to be having more archive errors:

![image](https://github.com/status-im/infra-status/assets/2212681/325d2c7e-9473-4f96-b330-6672b499d513)

But insert duration graph looks fine:

![image](https://github.com/status-im/infra-status/assets/2212681/79808a20-640c-4d2a-964e-0adec627aff0)

**Comment by jakubgs** [comment]
Also, the fact that we can't reasonably deduce if there are messaging reliability issues by looking at our fleet graphs show that we are either not exposing the right metrics, or we are not graphing them.

**Comment by jm-clius** [comment]
Note that the message reliability issues reported are related to filter, which is not currently enabled on the fleet. Any issues is therefore unlikely to be _directly_ related to the `prod` fleet or to be fixed by a downgrade. A better guess is that filter only worked because of some coincidental interconnectivity with another fleet that had filter enabled and this interconnectivity was broken after the upgrade. The first step therefore would be to add filter support to the prod fleet rather than downgrade. The metric inconsistencies or unexplained behaviour in the comments above may indeed warrant an investigation, but to me it seems likely orthogonal to what is currently reported for `filter`.

**Comment by jakubgs** [comment]
Now that's funny, we were debugging "reliability" of `filter` protocol when it wasn't even enabled:

![1656423887747](https://github.com/status-im/infra-status/assets/2212681/5b277439-438d-4279-9307-dc74421df2ef)

Here's the fix:

- https://github.com/status-im/infra-status/commit/1fb6de29 - status: enable filter protocol for prod
