### ISSUE TITLE
Switch Status fleet to use PostgreSQL DB

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-status-legacy#37]
The SQLite database is unmaintainable due to being single threaded, blocking queries when pruning,  and vacuuming requiring twice the size of the DB to complete.

We need to introduce PostgreSQL DB to this fleet gradually, to eventually reflect the same setup as [`infra-shards`](https://github.com/status-im/infra-shards) fleet.

1. Introduce a single database to `status.test` fleet to measure performance and latency.
2. Introduce a single database to `status.prod` if performance is satisfactory.
3. Develop a way to synchronize multiple Postgres instances across data centers on `status.test` fleet.
4. Switch `status.prod` fleet to multiple Postgres instances with database sync.
5. Eventually switch to synchronization managed by Waku nodes themselves.

**Comment by jakubgs** [comment]
Some improvements to our PostgreSQL HA role:

- [`infra-role-postgres-ha#8fcbe906`](https://github.com/status-im/infra-role-postgres-ha/commit/8fcbe906) - defaults: fix variable name for DB UID
- [`infra-role-postgres-ha#bbdb294e`](https://github.com/status-im/infra-role-postgres-ha/commit/bbdb294e) - databases: use initdb folder to create DBs and users
- [`infra-role-postgres-ha#a38d2c70`](https://github.com/status-im/infra-role-postgres-ha/commit/a38d2c70) - config: add admin.sh wrapper script
- [`infra-role-postgres-ha#35568e2e`](https://github.com/status-im/infra-role-postgres-ha/commit/35568e2e) - hba: wait for DB port to be available

**Comment by jakubgs** [comment]
More fixes for the Postgres role:

- [`infra-role-postgres-ha#716732b1`](https://github.com/status-im/infra-role-postgres-ha/commit/716732b1) - hba: use docker_compose task to restart
- [`infra-role-postgres-ha#8381b623`](https://github.com/status-im/infra-role-postgres-ha/commit/8381b623) - backup.sh: move to scripts dir
- [`infra-role-postgres-ha#a96ac903`](https://github.com/status-im/infra-role-postgres-ha/commit/a96ac903) - admin.sh: quote extra arguments to fix use of -e
- [`infra-role-postgres-ha#97f525e9`](https://github.com/status-im/infra-role-postgres-ha/commit/97f525e9) - consul: add health.sh to check replica status

**Comment by jakubgs** [comment]
Even more Postgres improvements:

- [`infra-role-postgres-ha#1ee52ded`](https://github.com/status-im/infra-role-postgres-ha/commit/1ee52ded) - meta: add missing infra roles to dependencies
- [`infra-role-postgres-ha#1ff92d5f`](https://github.com/status-im/infra-role-postgres-ha/commit/1ff92d5f) - hba: make optional when there's no replica
- [`infra-role-postgres-ha#6b296be1`](https://github.com/status-im/infra-role-postgres-ha/commit/6b296be1) - consul: add handling DB without replica to health.sh

Here's `infra-status` changes:

- [`infra-status#19b15072`](https://github.com/status-im/infra-status/commit/19b15072) - nodes.tf: rename to node.tf, and module to node
- [`infra-status#482bb74f`](https://github.com/status-im/infra-status/commit/482bb74f) - node.tf: rename group to status-node
- [`infra-status#8acf2ace`](https://github.com/status-im/infra-status/commit/8acf2ace) - add single db-01.do-ams3.status.test host
- [`infra-status#b277afa7`](https://github.com/status-im/infra-status/commit/b277afa7) - requirements: use full names of infra roles
- [`infra-status#f7c4b8a7`](https://github.com/status-im/infra-status/commit/f7c4b8a7) - outputs.tf: add to print list of hosta after TF run
- [`infra-status#10437a6c`](https://github.com/status-im/infra-status/commit/10437a6c) - status-db: add PostgreSQL DB configuration

The `db-01.do-ams3.status.test` host is up and running. The `status.prod` fleet won't be touched for a while.

**Comment by jakubgs** [comment]
I also had to enable `-d:postgres` flag for postgres build.

- [`nwaku#7a376f59`](https://github.com/waku-org/nwaku/commit/7a376f59) - chore: Adding -d:postgres flag when creating a Docker image for release and PRs (#2076)

It was enabled by default but the job didn't pick it up.

**Comment by jakubgs** [comment]
I tried configuring the node on `node-01.do-ams3.status.test` to use the DB but it's failing with:
```
 ERR 2023-11-23 12:37:19.449+00:00 4/7 Mounting protocols failed              topics="wakunode main" tid=1 file=wakunode2.nim:89
    error="failed to mount waku archive protocol: error in mountArchive: failed execution of retention policy: failed to get Page size: "
```
No idea what that's about, looks like a bug in `master`, I will try to build `v0.22.0` release.

**Comment by jakubgs** [comment]
I've built `v0.22.0` but it has the same issue. Building `v0.21.0` did resolve it though. Opened an issue:

* https://github.com/waku-org/nwaku/issues/2242

**Comment by jakubgs** [comment]
The `shards.test` fleet is running `aeb77a3e` which is current master but doesn't have this problem:
```
admin@store-01.do-ams3.shards.test:~ % d
CONTAINER ID   NAMES            IMAGE                              CREATED        STATUS
920badb37699   nim-waku-store   wakuorg/nwaku:deploy-shards-test   20 hours ago   Up 20 hours (healthy)

admin@store-01.do-ams3.shards.test:~ % d inspect wakuorg/nwaku:deploy-shards-test | grep commit
                "commit": "aeb77a3e",
```

**Comment by jakubgs** [comment]
Turns out:

>We have a bug related to the "size" retention policy that doesn't work if the database doesn't exist.
>In order to allow the node to start, let's change to either the "time" or "capacity" retention policies:
>```
>capacity:20000000
>```

**Comment by jakubgs** [comment]
Indeed, I can confirm setting the retention not based on `size` does fix the issue at startup:
```
admin@node-01.do-ams3.status.test:~ % d
CONTAINER ID   NAMES      IMAGE                              CREATED         STATUS
3d6868ff0701   nim-waku   wakuorg/nwaku:deploy-status-test   2 minutes ago   Up 2 minutes (healthy)
```

- [`infra-status#e6646aaa`](https://github.com/status-im/infra-status/commit/e6646aaa) - status-node: drop use of broken size retention policy

**Comment by jakubgs** [comment]
Notes from call we had today with John, Hanno, Andrea, and Ivan:

* App devs and QA have issues with historical messages appearing very later, even days later.
  - This is most probably due to split-brain between SQLite DBs between nodes and connecting to different nodes.
* We need to solve this problem in 3 steps:
  1. Use one DB across multiple DCs to see if it works, since it's the simplest.
  2. Switch to some kind of multi-master or sync or master-slave with LB as a middle ground.
  3. Wait for waku to implement actual syncing between nodes on protocol level.
* All of this is necessary since we have Status app dogfooding coming soon.
* Jakub is testing single DB in `status.test` and if it works we'll do the same for `status.prod`.
* Hanno believes the `shards.test` fleet setup with more than one waku node per DB in DC solves this problem.
  - This is actually not confirmed and is kinda speculation.
* Andrea wants a single DC `shards.dogfood` fleet to eliminate variables, as a stable reference point.
  - Jakub mostly agrees with this, as a good way to establish what works.
* Jakub would prefer if Hannos version was correct, and we could have separate DBs in different DCs.
  - If this doesn't work we'll need some kind of multi-master or syncing between DCs until waku implements it.

**Comment by jakubgs** [comment]
All nodes in `status.test` fleet are currently using the single PostgreSQL database:
```
 > a status-node -a 'grep db-url /docker/nim-waku/docker-compose.yml | sed "s/:.*@/:PASSWORD@/"'
node-01.do-ams3.status.test | CHANGED | rc=0 >>
      --store-message-db-url=postgres:PASSWORD@db-01.do-ams3.status.test.wg:5432/nim-waku
node-01.gc-us-central1-a.status.test | CHANGED | rc=0 >>
      --store-message-db-url=postgres:PASSWORD@db-01.do-ams3.status.test.wg:5432/nim-waku
node-01.ac-cn-hongkong-c.status.test | CHANGED | rc=0 >>
      --store-message-db-url=postgres:PASSWORD@db-01.do-ams3.status.test.wg:5432/nim-waku
```
@Ivansete-status you can start your research into performance of this layout.
I will be also monitoring metrics for this fleet.

**Comment by Ivansete-status** [comment]
I changed the default pubsub topic used by the `status.test` fleet so that we don't spam the `status.prod` fleet.
from: `/waku/2/default-waku/proto`
to: `/waku/2/default-waku-test/proto`

**Comment by Ivansete-status** [comment]
We need to create a `v0.22.1` version that at least contains the following commit: https://github.com/waku-org/nwaku/commit/aeb77a3e7595b5ca6f5db15c78503c1c0e01ee5b

With the current version used by `status.test` rows can't be added to the database due to:
```
ERR 2023-11-28 18:36:44.089+01:00 failed to insert message                   topics="waku archive" tid=197497 file=archive.nim:111 err="failed to insert into database: ERROR:  null value in column \"messagehash\" of relation \"messages\" violates not-null constraint
```

**Comment by jakubgs** [comment]
You killed the DB storage dude:

![image](https://github.com/status-im/infra-status/assets/2212681/eaf05ab9-7056-4762-a2e4-5af73ee0e2b8)

It's full:
```
admin@db-01.do-ams3.status.test:~ % df -h /data
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda         40G   38G     0 100% /data
```

**Comment by jakubgs** [comment]
The cause is obvious:

![image](https://github.com/status-im/infra-status/assets/2212681/320b844f-7276-4066-846b-e9331c8c3970)

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: dashboard created (https://grafana.infra.status.im/d/svkljKHSz/comparing-store-nodes?orgId=1) to allow easy _Store_ / _Archive_ performance comparison for `status.test` with one single database. The report with results is: https://www.notion.so/Migrate-status-test-to-PostgreSQL-e108b89fd9d34de2be13d10f42c92185
- _next_: change database configuration/layout to get better results.

**Comment by jakubgs** [comment]
The database host is full again:
```
admin@db-01.do-ams3.status.test:~ % df -h /docker
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda         40G   38G     0 100% /docker
```
And all nodes are unavailable:

![image](https://github.com/status-im/infra-status/assets/2212681/49cc3ef3-8ff0-49c1-9954-73aaaa4c39fc)

Due to inability to access the DB:
```
ERR 2023-12-04 10:52:49.012+00:00 4/7 Mounting protocols failed
  topics="wakunode main" tid=1 file=wakunode2.nim:89
  error="failed to setup archive driver: error creating table: error in createMessageTable: connRes.isErr in query: failed to stablish a new connection: exception opening new connection: connection to server at \"db-01.do-ams3.status.test.wg\" (10.10.0.199), port 5432 failed: FATAL:  the database system is not yet accepting connections\nDETAIL:  Consistent recovery state has not been yet reached.\n"
```

**Comment by jakubgs** [comment]
Gone in ~9 hours on the 2nd:

![image](https://github.com/status-im/infra-status/assets/2212681/878fcb61-cfa9-45cd-9186-3402279b6d83)

**Comment by Ivansete-status** [comment]
@jakubgs - I'll review the retention policy to enhance the database size issues.

On the other hand, the study concludes that latency doesn't play a big role in the performance issues because the three nodes (AMS, HK, US) behave equally regarding _Store_ timing and inserts (more details at https://www.notion.so/Migrate-status-test-to-PostgreSQL-e108b89fd9d34de2be13d10f42c92185 .)

![image](https://github.com/status-im/infra-status/assets/128452529/6d58bfca-45d2-4bcd-b45c-384535872c62)

![image](https://github.com/status-im/infra-status/assets/128452529/bb6c026c-4af2-4841-a82d-321a708065e2)

The major bottleneck is the current `db-01.do-ams3.status.test` configuration (Digital Ocean s-1vcpu-2gb)

**Comment by jakubgs** [comment]
Considering we didn't see much swapping I don't think memory is the main bottleneck:

![image](https://github.com/status-im/infra-status/assets/2212681/fcc634f9-bb50-469f-ba6a-b8111e8b9b42)

I have increased the host size to `s-2vcpu-2gb`, adding on vCPU, but not increasing memory size:

- [`infra-status#38540fd1`](https://github.com/status-im/infra-status/commit/38540fd1) - status.test: upgrade DB instance to s-2vcpu-2gb

Lets see what that does.

**Comment by Ivansete-status** [comment]
The performance was enhanced after increasing the database machine to `s-2vcpu-2gb`.

![image](https://github.com/status-im/infra-status/assets/128452529/e26a1c55-4b8c-4425-8c5d-dd7fbfc2bfc5)
![image](https://github.com/status-im/infra-status/assets/128452529/b955d500-dd40-4f99-a1b2-df8ed880a0c1)

**Comment by jakubgs** [comment]
Looks to me like the latency of queries in non-Amsterdam DCs is very bad, if I'm reading this correctly.

Most queries are in 2.5s and 5s buckets. That's not really acceptable for an interactive application.

**Comment by jakubgs** [comment]
I don't think benchmark is useful since it appears you are just overwhelming the host with the most traffic you can generate:

![image](https://github.com/status-im/infra-status/assets/2212681/dcb88183-d38e-467b-9741-931b9dc70076)

![image](https://github.com/status-im/infra-status/assets/2212681/7a042267-921d-47a1-a040-ae1d88b6d009)

All you're testing this way is "if I throw everything I can at the host will it work?", no, it won't, that's not a useful learning.

We want to see how the performance looks like with low traffic, normal traffic, and then traffic on the edge, but just generating maximum amount possible and then saying "look, it was overwhelmed" is not useful. A proper benchmark should show how a system behaves under different levels of stress, low, normal, high(or more).

What you're doing is like testing a home water installation by pumping water into it at 50 Bar and then being surprised it bursts.

**Comment by jakubgs** [comment]
Also, remember that the performance of queries isn't only dependent on the DB instance performance, but also on waku nodes.

**Comment by Ivansete-status** [comment]
Thanks so much for the brilliant insights! I'm performing a more realistic test now, considering the current use of `status.prod` fleet.

![image](https://github.com/status-im/infra-status/assets/128452529/fa4cb310-e2b7-48b9-b568-ff18f895faa3)
With that, I'll configure the `waku-store-request-generator` to have 10 users performing 1 _Store_ req / second, which turns into ~600 Store_req / minute

![image](https://github.com/status-im/infra-status/assets/128452529/9f9c6849-d7a9-4cb7-8703-499c2f33b034)

On the other hand, and considering the above image, I'll configure a `nwaku` node to publish one message every 0.06 seconds, aiming to generate a traffic of ~1000 msgs / minute, with an average size.

**Comment by Ivansete-status** [comment]
With the configuration described in my previous comment, it is evident that the Sore / Insert times are affected by the distance between the datacenters and the database. Notice that the performance is better with `s-2vcpu-2gb` but the network distance brings a big impact.
![image](https://github.com/status-im/infra-status/assets/128452529/d3c3f284-6071-49dc-80ef-068a3df4ea8a)
![image](https://github.com/status-im/infra-status/assets/128452529/e611f50c-424a-4a23-8014-d25c3c3d171b)

**Comment by jakubgs** [comment]
The `TERM` signal's you've been seeing are leftovers of a restart service that were not cleaned up:
```
~/work/infra-role-nim-waku master
 > g sl | grep restart
a93a85b  2023-02-15 14:21:20 +0100 Jakub Sokołowski     > drop temporary container restarts 
686ee11  2022-10-11 09:26:12 +0200 Jakub Sokołowski     > docker: restart every 6 hours instead 
b22e070  2022-10-06 12:20:07 +0200 Jakub Sokołowski     > docker: add temporary restart every 12 hours 
```
```
admin@node-01.do-ams3.status.test:~ % s cat restart-nim-waku.timer  
# /etc/systemd/system/restart-nim-waku.timer
[Unit]
After=multi-user.target

[Timer]
Persistent=yes
OnCalendar=00/06:00
RandomizedDelaySec=11600

[Install]
WantedBy=timers.target
```
I have now removed it from all `status.test` hosts.

**Comment by jakubgs** [comment]
Also removed from `node-01.gc-us-central1-a.status.prod` to see if we can remove it from `status.prod` without issues.

Originally this was a temporary "solution" to socket leaks:

- [`infra-role-nim-waku#b22e0705`](https://github.com/status-im/infra-role-nim-waku/commit/b22e0705) - docker: add temporary restart every 12 hours

**Comment by jakubgs** [comment]
Bumped DB node to `s-6vcpu-16gb`, but this is just a temporary change to do benchamrking:

- [`infra-status#4d77e063`](https://github.com/status-im/infra-status/commit/4d77e063) - status.test: upgrade DB instance to s-6vcpu-16gb

The DigitalOcean prices are not practical for long-term, and if we need big DB hosts we're going to have to start using physical hosts to save money. But i'm happy to leave this host as is till new year's and then downsize it, or replace with a physical one.

**Comment by Ivansete-status** [comment]
New test is launched by re-configuring the database with the following settings (https://pgtune.leopard.in.ua/)
```
-- DB Version: 15
-- OS Type: linux
-- DB Type: web
-- Total Memory (RAM): 16 GB
-- CPUs num: 6
-- Data Storage: ssd

ALTER SYSTEM SET
 max_connections = '200';
ALTER SYSTEM SET
 shared_buffers = '4GB';
ALTER SYSTEM SET
 effective_cache_size = '12GB';
ALTER SYSTEM SET
 maintenance_work_mem = '1GB';
ALTER SYSTEM SET
 checkpoint_completion_target = '0.9';
ALTER SYSTEM SET
 wal_buffers = '16MB';
ALTER SYSTEM SET
 default_statistics_target = '100';
ALTER SYSTEM SET
 random_page_cost = '1.1';
ALTER SYSTEM SET
 effective_io_concurrency = '200';
ALTER SYSTEM SET
 work_mem = '6990kB';
ALTER SYSTEM SET
 huge_pages = 'off';
ALTER SYSTEM SET
 min_wal_size = '1GB';
ALTER SYSTEM SET
 max_wal_size = '4GB';
ALTER SYSTEM SET
 max_worker_processes = '6';
ALTER SYSTEM SET
 max_parallel_workers_per_gather = '3';
ALTER SYSTEM SET
 max_parallel_workers = '6';
ALTER SYSTEM SET
 max_parallel_maintenance_workers = '3';
 
 ```

**Comment by Ivansete-status** [comment]
After upgrading to a more powerful database machine, we still can see low _Store_ / _Archive_ performance on both US and HK nodes:
![image](https://github.com/status-im/infra-status/assets/128452529/c216a9db-68d0-4e11-8330-8fce3e123afe)

( cc @jakubgs )

**Comment by jakubgs** [comment]
Yes, I think now we can clearly conclude that the single DB used from different data centers is not a viable solution.

Our options are:

* Run a setup with just one DC to completely avoid the split-brain failure state. Not a real solution.
* Figure out if the new `shards.test` fleet with multiple store nodes per DB don't solve this issue.
* Figure out a way to sync DBs across data centers. With some form of mulit-master setup or other sync method.

Thanks for researching this. I am going on holiday break till 2nd of January so I will not be working on this for a while.
If help is needed please ask Anton or Alexis, but please don't make major changes to fleets without my input.

**Comment by jakubgs** [comment]
Since the benchmarks revealed that the single-DB cross-DC setup does not work I'm upgrading the layout to use multiple DBs:

- [`infra-status#02b75ec6`](https://github.com/status-im/infra-status/commit/02b75ec6) - switch to multi-DB layout with one DB per DC

The new setup has been deployed and works:

![image](https://github.com/status-im/infra-status/assets/2212681/72d529b3-883b-43ae-8e30-0a6b006ee27a)

Will do `status.prod` tomorrow.

**Comment by jakubgs** [comment]
I have switched `status.prod` to use multiple hosts with PostgreSQL:

- [`infra-status#fe58d7f6`](https://github.com/status-im/infra-status/commit/fe58d7f6) - workspaces.tf: fix instance type for GC DB hosts
- [`infra-status#ff28064f`](https://github.com/status-im/infra-status/commit/ff28064f) - status: add DB hosts for prod fleet

There's an issue with DB initialization. Will debug tomorrow.

**Comment by jakubgs** [comment]
Found the issue, lack of stage in DB hostname:

- [`infra-status#e8b5ff25`](https://github.com/status-im/infra-status/commit/e8b5ff25) - status-node: fix missing stage for DB hostname

Had to also build a fresh `deploy-status-prod-trace` image:
https://ci.infra.status.im/job/nim-waku/job/deploy-status-prod-trace/3/
But for some reason it was just restarting without an error, so i manually switched it to a normal one.

The fleet is back up and working:

![image](https://github.com/status-im/infra-status/assets/2212681/df9cce53-7dc8-49f3-8e73-12b4185f35c9)
