### ISSUE TITLE
Cannot connect to `shards.*` fleets via websocket

### ISSUE THREAD

**Issue by felicio** [status-im/infra-status-legacy#41]
## what

- localhost logs https://gist.github.com/felicio/6f9eac25d18057a0fa35be05cd1e646e
  - `libp2p:mss:handle respond with "na" for "/vac/waku/metadata/1.0.0" +0ms`
  - `libp2p:upgrader:error could not create new stream for protocols [ '/vac/waku/store/2.0.0-beta4' ] on connection with address`
  - `libp2p:mplex:stream:initiator:2 abort with error Error: stream ended before 1 bytes became available`
  - `waku:error:stream-manager:/vac/waku/store/2.0.0-beta4 Failed to prepare a new stream for`
  - `throw new Error("Failed to get a connection to the peer");`
- server logs https://kibana.infra.status.im/goto/92c9b1c0-b388-11ee-aaa4-85391103106b
  - `"waku metadata codec not supported: Unable to select sub-protocol @["/vac/waku/metadata/1.0.0"]"`

## how

- using light node `"@waku/sdk": "^0.0.21"`

## where

- for example `/dns4/store-01.do-ams3.shards.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT`

**Comment by felicio** [comment]
@apentori @yakimant @danisharora099 could you please have a look or mention someone who could?

**Comment by danisharora099** [comment]
@felicio, @apentori seems to think it's related to some of the infra bugs from the weekend. 
please let me know if that does not resolve it and I can help look for other reasons

**Comment by apentori** [comment]
Working on it to solve the issue.

The `waku.test`  fleet is currently down.

**Comment by felicio** [comment]
@danisharora099 @apentori I'm afraid it's not related. I've first encountered the issue back in December. Also, it's `shards.test` and not `waku.test`.

Thanks in advance that you'll look into it.

**Comment by danisharora099** [comment]
@apentori can you please confirm?

@felicio can you confirm if you can spin a local waku node and are able to connect to it?

**Comment by felicio** [comment]
@danisharora099 I'm sorry, but the above is the only debugging I had time to do atm.

**Comment by apentori** [comment]
I confirm it's not realated to the issue i was thinking. `shards.test` doesn't have an RLN connection. 

The ws connection seems to work for  me for the `store` node as described in the [waku docs](https://docs.waku.org/guides/js-waku/debug-waku-dapp/) :
```bash
$ websocat -v wss://store-01.do-ams3.shards.test.statusim.net:443
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
[INFO  websocat::ws_peer] incoming None
```

However it fails for a `boot` node : 
```bash
$ websocat -v wss://boot-01.do-ams3.shards.test.statusim.net:433
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
websocat: WebSocketError: I/O failure
websocat: error running
```

**Comment by apentori** [comment]
The boot node is working fine, it was a port mistake on my part:

```bash
$ websocat -v -k  wss://boot-01.do-ams3.shards.test.statusim.net:443
[INFO  websocat::lints] Auto-inserting the line mode
[INFO  websocat::stdio_threaded_peer] get_stdio_peer (threaded)
[INFO  websocat::ws_client_peer] get_ws_client_peer
[INFO  websocat::ws_client_peer] Connected to ws
[INFO  websocat::ws_peer] incoming None
[INFO  websocat::sessionserve] Reverse finished
```

**Comment by felicio** [comment]
Just wanted to add real quick that I don't think it tests any of the protocols, like https://github.com/status-im/infra-hq/issues/92#issue-1769478385 would, given the errors in the issue description.

**Comment by felicio** [comment]
@danisharora099 please, did you manage to check this one out?

**Comment by danisharora099** [comment]
I think I see what the problem might be:
It might be possible that the multiaddr that you're using to connect with, uses The Waku Network, while your js-waku node might not have been started with any shard information.
Can you please share an exact code snippet for the way you are starting your js-waku node? 

This thread might be helpful as well: https://discord.com/channels/1110799176264056863/1206888344533864479

I will take a much closer look at this thread's notifications moving forward. @felicio

**Comment by felicio** [comment]
For me the error was resolved by upgrading the waku dependencies.
