### ISSUE TITLE
Node stuck attempting to load messages from persistent storage

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-status-legacy#5]
Our nodes on both test and prod fleets appear to be stuck on this log message:
```
INF 2022-03-12 10:36:02.348+00:00 attempting to load messages from persistent storage topics="wakustore" tid=1 file=waku_store.nim:359
```
And it's not responding to API calls:
```
admin@node-01.gc-us-central1-a.status.test:/docker/nim-waku % /docker/nim-waku/rpc.sh get_waku_v2_debug_v1_info
curl: (7) Failed to connect to localhost port 8545: Connection refused
```
This is true for all most on both test and prod fleets. And they are all running `cf271903`.

**Comment by jakubgs** [comment]
Purging the `data/store.sqlite3` file appears to fix the issue.
```
admin@node-02.gc-us-central1-a.status.prod:/docker/nim-waku % rm -fr data/store.sqlite3
admin@node-02.gc-us-central1-a.status.prod:/docker/nim-waku % dc up -d
Creating network "nim-waku_default" with the default driver
Creating nim-waku ... done

admin@node-02.gc-us-central1-a.status.prod:/docker/nim-waku % d
CONTAINER ID   NAMES      IMAGE                                    CREATED         STATUS
69487de290c6   nim-waku   statusteam/nim-waku:deploy-status-prod   7 seconds ago   Up 6 seconds (health: starting)

admin@node-02.gc-us-central1-a.status.prod:/docker/nim-waku % /docker/nim-waku/rpc.sh get_waku_v2_debug_v1_info
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "listenAddresses": [
      "/dns4/node-02.gc-us-central1-a.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAmDQugwDHM3YeUp86iGjrUvbdw3JPRgikC7YoGBsT2ymMg"
    ]
  }
}
```

**Comment by jm-clius** [comment]
Haven't noticed this on any other fleets yet.

Perhaps something is slowing down the loading from DB and there were just more stored messages on the Status fleets. What level of logging is enabled on the Status fleets and do they have `--store-capacity` set?

**Comment by jakubgs** [comment]
We use the default of 10 k for store capacity limit:
```
admin@node-01.do-ams3.status.test:/docker/nim-waku % grep store docker-compose.yml
      --store=true
      --store-capacity=10000
```
https://github.com/status-im/infra-role-nim-waku/blob/9e0ad629/defaults/main.yml#L37-L38

**Comment by jakubgs** [comment]
It's worth noting that `node-02.gc-us-central1-a.status.prod` also had this issue. Which also had it's DB purged:
```
admin@node-02.gc-us-central1-a.status.prod:~ % sudo stat /docker/nim-waku/data/store.sqlite3
  File: /docker/nim-waku/data/store.sqlite3
  Size: 4096      	Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d	Inode: 774149      Links: 1
Access: (0644/-rw-r--r--)  Uid: (100000/dockremap)   Gid: (100000/dockremap)
Access: 2022-03-12 10:39:51.760453117 +0000
Modify: 2022-03-12 10:39:51.756452749 +0000
Change: 2022-03-12 10:39:51.756452749 +0000
 Birth: -
```

**Comment by jakubgs** [comment]
I've set the log level on `node-02.gc-us-central1-a.status.prod` to `trace` to debug this issue if it comes up again: https://github.com/status-im/infra-status/commit/ec7f6608

**Comment by jakubgs** [comment]
Although I don't see any `TRC` level logs:
```
admin@node-02.gc-us-central1-a.status.prod:/docker/nim-waku % awk '{a[$3]++}END{for(n in a){printf "%s - %d\n", n, a[n]}}' /var/log/docker/nim-waku/docker.log
ERR - 2
INF - 64
DBG - 4464
admin@node-02.gc-us-central1-a.status.prod:/docker/nim-waku % grep log docker-compose.yml 
      --log-level=trace
```

**Comment by jakubgs** [comment]
Oh, looks like the binary needs to be also compiled with `-d:chronicles_log_level=TRACE`, but that will cause all nodes to run with `tracel` level logs, which is quite awful, as `--log-level` flag is then ignored. I've reverted the commit I made above.

Instead I will build the `test` fleet image with trace logs enabled.

**Comment by jakubgs** [comment]
Done: https://ci.status.im/job/nim-waku/job/deploy-status-test/3/

**Comment by jakubgs** [comment]
It appears this is a reoccurring issue, and on `node-02.ac-cn-hongkong-c.status.prod` it took ~20 minutes to start:
```
INF 2022-03-14 21:02:10.806+00:00 attempting to load messages from persistent storage topics="wakustore" tid=1 file=waku_store.nim:359
INF 2022-03-14 21:20:51.503+00:00 successfully loaded from store             topics="wakustore" tid=1 file=waku_store.nim:366
```
Considering the store is less than 3 GB I'm not sure what's taking so long:
```
admin@node-02.ac-cn-hongkong-c.status.prod:~ % sudo du -hsc /docker/nim-waku/data/store.sqlite3
2.7G	/docker/nim-waku/data/store.sqlite3
2.7G	total
```
@jm-clius what does "load messages" entail?

**Comment by jakubgs** [comment]
Now isn't this an interesting disk usage pattern...

![image](https://user-images.githubusercontent.com/2212681/158265664-c342dcce-e283-4284-b8ab-3e3c6fba3522.png)

**Comment by jakubgs** [comment]
Looks like reads kept growing over tim until they reach 100% and then we lose metrics for the node:

![image](https://user-images.githubusercontent.com/2212681/158265929-19c494da-fc10-42ec-ae9a-44daef3a5aaa.png)

At that point we reach some ridiculous CPU load, which probably kills handling of any kind of connections:

![image](https://user-images.githubusercontent.com/2212681/158266023-13b71cdc-8d47-4de9-ac26-02fc09232354.png)

**Comment by jakubgs** [comment]
But if we look at network traffic we see it doesn't grow together with disk reads:

![image](https://user-images.githubusercontent.com/2212681/158266117-ba3154ab-445e-4ca3-951e-1d82ef46f31a.png)

It's steady until the host becomes unresponsive.

**Comment by jakubgs** [comment]
The container also appears to start getting more memory page faults:

![image](https://user-images.githubusercontent.com/2212681/158266498-cb5349f7-b1a5-401a-b35e-d2090671abbb.png)

**Comment by jakubgs** [comment]
At 19:35 we hit the peak of wait time length for disk I/O operations:

![image](https://user-images.githubusercontent.com/2212681/158267793-202e97e5-874d-4e8f-94c7-f0e5714ad9bf.png)

Something is defintiely up with the store.

**Comment by jakubgs** [comment]
What the hell is this?!

![image](https://user-images.githubusercontent.com/2212681/158268281-2228b2af-87ec-4626-afb8-8dc2f4dd63ba.png)

Why are we putting topics in metrics?!

**Comment by jakubgs** [comment]
What the hell:
```
admin@node-01.do-ams3.status.prod:~ % c localhost:8008/metrics | grep '^waku_node_messages_total' | wc -l
1102
admin@node-01.do-ams3.status.prod:~ % c localhost:8008/metrics | grep '^waku_node_messages_total' | head -n2
waku_node_messages_total{type="relay",contentTopic="/waku/1/0x19d2ea3d/rfc26"} 91.0
waku_node_messages_total{type="relay",contentTopic="/waku/1/0xa0204a26/rfc26"} 34.0
```
[Prometheus is NOT designed for data with this level of cardinality.](https://prometheus.io/docs/practices/naming/#labels)

@jm-clius this needs to be fixed right away. For now I will ignore all these metrics in Prometheus.

**Comment by jakubgs** [comment]
I've dropped `waku_node_messages_total` metrics in the scrape job configuration in Prometheus: https://github.com/status-im/infra-hq/commit/3406a3f6

**Comment by jakubgs** [comment]
Created issue to fix this metric: https://github.com/status-im/nim-waku/issues/890

**Comment by jm-clius** [comment]
> @jm-clius what does "load messages" entail?

It reads the messages from the DB and:
1) computes an index for each message
2) inserts that message into the in-memory data structure

(1) we can likely remove completely, as we shouln't have to compute an index for a message that already exists in the database
(2) may be slow because it sorts messages on insert: no easy way to change the way the data structure forces sorting-on-insert, but perhaps we can split the loading process here into phases which happens in the background while the node becomes operational.

**Comment by jakubgs** [comment]
Well, yeah, the SQLite database should be indexing things, why would we re-index them on load? Weird.

**Comment by jakubgs** [comment]
And if there's some secret sauce to how we index things, why aren't we saving that index into the DB itself anyway?

**Comment by jm-clius** [comment]
> [Prometheus is NOT designed for data with this level of cardinality.](https://prometheus.io/docs/practices/naming/#labels)
> 
> @jm-clius this needs to be fixed right away. For now I will ignore all these metrics in Prometheus.

Agreed! Oversight from our side to not foresee the content topic explosion that would happen when a bridge gets enabled. Have opened PR for a fix here: https://github.com/status-im/nim-waku/pull/891

**Comment by jakubgs** [comment]
I'm disabling trace logs on test fleet, because the volume of logs is just absurd:

![image](https://user-images.githubusercontent.com/2212681/158481716-5790f8df-bc78-4611-9d1c-3b103045d569.png)

Literally ~30 GB of logs from just today. This is not sustainable for ElasticSearch.

CI Job: https://ci.status.im/job/nim-waku/job/deploy-status-test/4/

**Comment by jakubgs** [comment]
And I'm purging these logs from ES cluster because it will make querying far too slow:
```
 > ./esclean.py -p docker/nim-waku -i 'logstash-2022.03.*'      
Cluster: status-logs-search
logstash-2022.03.01    count:    66455
logstash-2022.03.02    count:    65122
logstash-2022.03.03    count:    67662
logstash-2022.03.04    count:    65692
logstash-2022.03.05    count:    65689
logstash-2022.03.06    count:    65653
logstash-2022.03.07    count:    67124
logstash-2022.03.08    count:    65748
logstash-2022.03.09    count:    68153
logstash-2022.03.10    count:   115299
logstash-2022.03.11    count:   120123
logstash-2022.03.12    count:   110123
logstash-2022.03.13    count:   108883
logstash-2022.03.14    count: 30180003
logstash-2022.03.15    count: 58051061
```

**Comment by jakubgs** [comment]
Looks like the `--store-capacity` flag is being ignored:
```
admin@node-01.do-ams3.status.prod:/docker/nim-waku % du -h data/store.sqlite3
4.4G    data/store.sqlite3

admin@node-01.do-ams3.status.prod:/docker/nim-waku % echo 'SELECT count(*) FROM Message;' | sudo sqlite3 data/store.sqlite3
2457569

admin@node-01.do-ams3.status.prod:/docker/nim-waku % grep store-capacity docker-compose.yml 
      --store-capacity=10000
```
It appears this might be the cause:

* https://github.com/status-im/nim-waku/issues/767

As found out by @kaiserd.

**Comment by kaiserd** [comment]
I further looked into this: As described in https://github.com/status-im/nim-waku/issues/767 , the DB can grow very large. (see @jakubgs post above).
While the `--store-capacity` (default 50k) limits what is actually loaded into the in-memory data structure, an [`ORDER BY` is ran on the whole DB](https://github.com/status-im/nim-waku/blob/2d6a2bec4774bb192c3e6493da0cd484f6bfcd06/waku/v2/node/storage/message/waku_message_store.nim#L122)

This operation also explains the high disk usage plots posted by @jakubgs.

I assume, solving https://github.com/status-im/nim-waku/issues/767 will solve this issue, too. I will  further look into this.

**Comment by jm-clius** [comment]
Good catch, @kaiserd! Thanks.

Periodically truncating the table may be a good workaround as a minimal fix, until we have proper disk management in the `store`.

**Comment by kaiserd** [comment]
I added a PR with a simple fix: https://github.com/status-im/nim-waku/pull/900

**Comment by kaiserd** [comment]
Two more things I noticed that could improve DB loading performance:

* Use `receiverTimestamp` as part of the primary key instead of `senderTimestamp` (addressed in the PR mentioned in my last post)
* Introduce an index on `receiverTimestamp`. Even when using `receiverTimestamp` as part of the primary key, sqlite3 will still generate a temporary B-tree for sorting-operations like `ORDER-BY`

I could introduce this index in a separate small PR or wait for an issue + PR introducing a more efficient DB structure.
This new DB structure would also avoid recalculating indexes and more improvements. I will discuss this with @jm-clius

**Comment by kaiserd** [comment]
I added a further issue regarding the efficiency issues I mentioned in my last post.
https://github.com/status-im/nim-waku/issues/914

While the second point stands and is addressed in this issue, the first point (using `senderTimestamp` as part of the primary key) will not work for now, because the `senderTimestamp` might not be set. I gave a little background in the linked issue.

**Comment by jakubgs** [comment]
Since https://github.com/status-im/nim-waku/pull/900 was merged I'm going to deploy a fresh build to the `status.test` fleet:
https://ci.status.im/job/nim-waku/job/deploy-status-test/5/

And looks like `wakuv2.test` already has the changes:
https://ci.status.im/job/nim-waku/job/deploy-v2-test/323/

**Comment by jakubgs** [comment]
We can see the log message added in the PR:
```
admin@node-01.do-ams3.status.test:~ % grep 'number of messages' /var/log/docker/nim-waku/docker.log     
2022-03-29T10:18:09.470672+00:00 docker/nim-waku[820]: DBG 2022-03-29 10:18:09.467+00:00 number of messages in sqlite database      topics="wakunode.setup" tid=1 file=waku_message_store.nim:95 messageNum=2604304
2022-03-29T10:20:53.886434+00:00 docker/nim-waku[820]: DBG 2022-03-29 10:20:53.886+00:00 the number of messages in the memory       topics="wakustore" tid=1 file=waku_store.nim:379 messageNum=10000
```
But I don't see any messages about deletions:
```
admin@node-01.do-ams3.status.test:~ % grep 'messages deleted' /var/log/docker/nim-waku/docker.log
admin@node-01.do-ams3.status.test:~ % 
```

**Comment by jakubgs** [comment]
It appears the messages are limited, but the size of the DB remains big because of lack of vacuuming:
```
admin@node-01.do-ams3.status.test:~ % sudo du -hsc /docker/nim-waku/data/store.sqlite3
4.5G	/docker/nim-waku/data/store.sqlite3
4.5G	total
admin@node-01.do-ams3.status.test:~ % echo 'SELECT count() FROM Message;' | sqlite3 /docker/nim-waku/data/store.sqlite3
12786
```
But it's weird I can't find the [debug message about deleting old messages](https://github.com/status-im/nim-waku/blob/52de0e434ffa25def7657a8babf0a456e52508a1/waku/v2/node/storage/message/waku_message_store.nim#L64).

EDIT: It appears this log is hidden under `when defined(debug):` which is a compile time flag.

**Comment by jakubgs** [comment]
Vacuuming makes a big diffeerence:
```
admin@node-01.do-ams3.status.test:~ % echo 'VACUUM;' | sudo sqlite3 /docker/nim-waku/data/store.sqlite3
admin@node-01.do-ams3.status.test:~ % sudo du -hsc /docker/nim-waku/data/store.sqlite3                 
26M	/docker/nim-waku/data/store.sqlite3
26M	total
```

**Comment by jakubgs** [comment]
One host doesn't appear to be cleaned up though:
```
admin@node-01.gc-us-central1-a.status.test:~ % grep 'number of messages' /var/log/docker/nim-waku/docker.log
2022-03-29T10:45:38.450723+00:00 docker/nim-waku[1493]: DBG 2022-03-29 10:45:38.400+00:00 number of messages in sqlite database      topics="wakunode.setup" tid=1 file=waku_message_store.nim:95 messageNum=865547

admin@node-01.gc-us-central1-a.status.test:~ % echo 'SELECT count() FROM Message;' | sqlite3 /docker/nim-waku/data/store.sqlite3
865547
```

**Comment by jakubgs** [comment]
The node is on the right commit:
```
admin@node-01.gc-us-central1-a.status.test:~ % d inspect statusteam/nim-waku:deploy-status-test | jq '.[].Config.Labels'
{
  "commit": "52de0e43",
  "description": "Wakunode: Waku and Whisper client",
  "maintainer": "jakub@status.im",
  "source": "https://github.com/status-im/nim-waku"
}
```

**Comment by jakubgs** [comment]
Are we SURE @kaiserd that we want to hide this debug line behind a debug compile flag(nice naming...):
https://github.com/status-im/nim-waku/blob/52de0e43/waku/v2/node/storage/message/waku_message_store.nim#L64

I think it's useful to see if the cleanup was actually done.

**Comment by jakubgs** [comment]
Oh, found something:
```
admin@node-01.gc-us-central1-a.status.test:~ % grep 'deleting' /var/log/docker/nim-waku/docker.log    
2022-03-29T10:45:38.474185+00:00 docker/nim-waku[1493]: WRN 2022-03-29 10:45:38.473+00:00 failed to init WakuMessageStore            topics="wakunode.setup" tid=1 file=wakunode2.nim:1031 err="deleting oldest messages failed"
```
Looks like `deleting oldest messages failed` for some reason. There's nothing to indicate the reason.

**Comment by jakubgs** [comment]
@kaiserd here's the store from that host: https://status-misc.ams3.digitaloceanspaces.com/nim_waku_store.sqlite3.tar.gz

**Comment by jm-clius** [comment]
Mmm. So far, what I assume to be the resulting `delete` query, works for me locally:
`DELETE FROM Message WHERE id NOT IN (SELECT id FROM Message ORDER BY receiverTimestamp DESC LIMIT 11500);`

With result:
```
sqlite> select count (*) from Message;
11500
```

It does take a couple of minutes to complete, though.

**Comment by jakubgs** [comment]
As suggested by @kaiserd it might be the issue on `node-01.gc-us-central1-a.status.test` was memory related:

![image](https://user-images.githubusercontent.com/2212681/160885392-b9fc4c4e-f35a-4d70-b741-deba412a4222.png)

Since that one has ~0.4 GB less RAM than the other two.

**Comment by kaiserd** [comment]
Oh sorry for overlooking the discussion here (had a day off yesterday)! But I think we covered everything in the nim-waku discord channel.

**Comment by kaiserd** [comment]
Here is a PR adding the vacuum:  https://github.com/status-im/nim-waku/pull/928

**Comment by kaiserd** [comment]
> Are we SURE @kaiserd that we want to hide this debug line behind a debug compile flag(nice naming...):
> https://github.com/status-im/nim-waku/blob/52de0e43/waku/v2/node/storage/message/waku_message_store.nim#L64

> I think it's useful to see if the cleanup was actually done.

Sorry for overlooking this. We could change this in a new PR.
The reason putting this behind a debug flag is because this requires and additional select query. But because it is run after the delete, it should not be too bad.
Unfortunally, the squlite3 `DELETE` statement does not return the number of deleted row.

As an alternative, we could print the part of the debug message that does not require this query.

**Comment by jakubgs** [comment]
I think it's fine if it doesn't include a count. I just want an indication that deletion was attempted.

**Comment by kaiserd** [comment]
Here it is: https://github.com/status-im/nim-waku/pull/929

**Comment by jakubgs** [comment]
I think this is resolved.
