### ISSUE TITLE
Deploy v0.10.0 to all fleets

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-status-legacy#9]
The new `v0.10.0` release includes multiple fixes we've been waiting for and is required for newest Desktop release:
https://github.com/status-im/nwaku/releases/tag/v0.10

This includes:

* Storing of messages in the SQLite database instead of memory, and querying them there as well.
* Fix for memory leak caused by prepared but unreleased SQL statements.
* Support for TOML config files(though I'd prefer JSON/YAML).
* Multiple fixes for Websocket support

**Comment by jakubgs** [comment]
It appears the release already got deployed to `wakuv2.*` fleets:

* https://ci.status.im/job/nim-waku/job/deploy-v2-test/345/
* https://ci.status.im/job/nim-waku/job/deploy-v2-prod/41/

So we only need to roll out the flag changes from these PRs:

* https://github.com/status-im/infra-role-nim-waku/pull/2
* https://github.com/status-im/infra-nim-waku/pull/51
* https://github.com/status-im/infra-status/pull/8

**Comment by jakubgs** [comment]
I have deployed the new flag changes to `wakuv2.test` and it exploded with:
```
Error while processing thesqlite-retention-time=30.days.seconds parameter: invalid integer: 30.days.seconds
```
And it appears that the flag is an `int64`:
```nim
    sqliteRetentionTime* {.
      desc: "time the sqlite-only store keeps messages (in seconds)",
      defaultValue: 30.days.seconds
      name: "sqlite-retention-time" }: int64 # TODO: Duration
```
https://github.com/status-im/nwaku/blob/6c8ab0ab0f76fe765d95ef2f7bfb88d691a18bf7/waku/v2/node/config.nim#L199-L202

**Comment by jakubgs** [comment]
Fixes for the retention flag format:

* https://github.com/status-im/infra-role-nim-waku/pull/3
* https://github.com/status-im/infra-nim-waku/pull/52
* https://github.com/status-im/infra-status/pull/10

**Comment by jakubgs** [comment]
Deployment of new flag values seems to work on `wakuv2.test`:
```
admin@node-01.do-ams3.wakuv2.test:/docker/nim-waku-v2 % grep SQLite /var/log/docker/nim-waku-v2/docker.log | tail -n1
2022-06-20T10:52:48.001671+00:00 docker/nim-waku-v2[750]: INF 2022-06-20 10:52:48.001+00:00 SQLite-only store initialized. Messages are *not* loaded into memory. topics="wakustore" tid=1 file=waku_store.nim:383
```
```
 > a all -a 'grep sqlite /docker/nim-waku-v2/docker-compose.yml'
node-01.do-ams3.wakuv2.test | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.gc-us-central1-a.wakuv2.test | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.ac-cn-hongkong-c.wakuv2.test | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
```

**Comment by jakubgs** [comment]
BTW, I noticed that the `v0.10` release was pointing to a commit not in the `master` branch:

![image](https://user-images.githubusercontent.com/2212681/174587851-ad73429d-02cc-49a5-a551-1756aa02d4ec.png)

But that was fixed by @LNSD. Now it points at: https://github.com/status-im/nwaku/commit/d754444f4515f5c8163bc7f396c8bd7bb26fe6cc

**Comment by jakubgs** [comment]
Not many metrics for store, but seems to look fine:

![image](https://user-images.githubusercontent.com/2212681/174588376-8a3d8577-c2c7-4c01-8b6d-0cb758bb1168.png)

I will deploy the flags to `prod` now.

**Comment by jakubgs** [comment]
Seems to work on `prod` fine as well:
```
admin@node-01.do-ams3.wakuv2.prod:~ % grep SQL /var/log/docker/nim-waku-v2/docker.log | tail -n1
2022-06-20T11:15:52.970704+00:00 docker/nim-waku-v2[774]: INF 2022-06-20 11:15:52.963+00:00 SQLite-only store initialized. Messages are *not* loaded into memory. topics="wakustore" tid=1 file=waku_store.nim:383
```

**Comment by jakubgs** [comment]
Changes deployed to `status.test` without issues:
```
 > a status -a 'grep sqlite /docker/nim-waku/docker-compose.yml'   
node-01.do-ams3.status.test | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.gc-us-central1-a.status.test | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.ac-cn-hongkong-c.status.test | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
```

**Comment by jakubgs** [comment]
Deployment on test fleet appears to have worked fine as well:
```
admin@node-01.do-ams3.status.test:~ % grep sqlite /var/log/docker/nim-waku/docker.log | tail -n1
2022-06-20T11:31:34.443634+00:00 docker/nim-waku[820]: INF 2022-06-20 11:31:34.440+00:00 SQLite-only store initialized. Messages are *not* loaded into memory. topics="wakustore" tid=1 file=waku_store.nim:383
```
Metrics look fine:

![image](https://user-images.githubusercontent.com/2212681/174595175-43e2144d-1b53-4fe4-8c90-b12cccd54021.png)

![image](https://user-images.githubusercontent.com/2212681/174595217-c35360dd-9ed7-4852-833d-25110d3f80e2.png)

**Comment by jakubgs** [comment]
And `status.prod` deployed as well:
```
admin@node-01.do-ams3.status.prod:~ % grep sqlite /var/log/docker/nim-waku/docker.log | tail -n1
2022-06-20T12:23:00.856977+00:00 docker/nim-waku[849]: INF 2022-06-20 12:23:00.850+00:00 SQLite-only store initialized. Messages are *not* loaded into memory. topics="wakustore" tid=1 file=waku_store.nim:383
```
```
 > a status -a 'grep sqlite /docker/nim-waku/docker-compose.yml'
node-02.do-ams3.status.prod | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.do-ams3.status.prod | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-02.gc-us-central1-a.status.prod | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.gc-us-central1-a.status.prod | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-02.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
node-01.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 >>
      --sqlite-store=true
      --sqlite-retention-time=2592000
```
Build: https://ci.status.im/job/nim-waku/job/deploy-status-prod/8/

**Comment by jakubgs** [comment]
I don't like how these messages metrics look:

![image](https://user-images.githubusercontent.com/2212681/174603783-f4c354ce-a87e-4231-b31b-7276b98d3b6a.png)
![image](https://user-images.githubusercontent.com/2212681/174603842-b958587b-1e84-424d-bb01-ea569a2b3e81.png)

But we do have peers connected:

![image](https://user-images.githubusercontent.com/2212681/174603880-b7e38c22-8fc7-479b-86b7-25329c7fbae9.png)
![image](https://user-images.githubusercontent.com/2212681/174603903-d070e4dd-bbf6-4c61-9266-81359712f3fb.png)

**Comment by jakubgs** [comment]
We do have the bridge connected:
```
 > a status -a "/docker/nim-waku/rpc.sh get_waku_v2_admin_v1_peers | jq '.result[].multiaddr' | grep 161.35.244.35"
node-01.do-ams3.status.prod | CHANGED | rc=0 >>
"/ip4/161.35.244.35/tcp/9000/p2p/16Uiu2HAm1JGyYjjraM95y9wK4WFjg7k79H1xAGWGU8FTXXczjcbW"
node-02.do-ams3.status.prod | CHANGED | rc=0 >>
"/ip4/161.35.244.35/tcp/9000/p2p/16Uiu2HAm1JGyYjjraM95y9wK4WFjg7k79H1xAGWGU8FTXXczjcbW"
node-01.gc-us-central1-a.status.prod | CHANGED | rc=0 >>
"/ip4/161.35.244.35/tcp/9000/p2p/16Uiu2HAm1JGyYjjraM95y9wK4WFjg7k79H1xAGWGU8FTXXczjcbW"
node-02.gc-us-central1-a.status.prod | CHANGED | rc=0 >>
"/ip4/161.35.244.35/tcp/9000/p2p/16Uiu2HAm1JGyYjjraM95y9wK4WFjg7k79H1xAGWGU8FTXXczjcbW"
node-02.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 >>
"/ip4/161.35.244.35/tcp/9000/p2p/16Uiu2HAm1JGyYjjraM95y9wK4WFjg7k79H1xAGWGU8FTXXczjcbW"
node-01.ac-cn-hongkong-c.status.prod | CHANGED | rc=0 >>
"/ip4/161.35.244.35/tcp/9000/p2p/16Uiu2HAm1JGyYjjraM95y9wK4WFjg7k79H1xAGWGU8FTXXczjcbW"
```
But it appears the image is old:
```
admin@bridge-01.do-ams3.status.prod:~ % d ps -a
CONTAINER ID   NAMES             IMAGE                                    CREATED       STATUS
afa99269a67a   nim-waku-bridge   statusteam/nim-waku:deploy-bridge-prod   4 weeks ago   Up 4 weeks
```
So I've started builds for that as well:

* https://ci.status.im/job/nim-waku/job/deploy-bridge-test/6/
* https://ci.status.im/job/nim-waku/job/deploy-bridge-prod/4/

**Comment by jakubgs** [comment]
It appears the version of the bridge was indeed the problem:

![image](https://user-images.githubusercontent.com/2212681/174607443-cd7bc29a-1e55-4026-a86b-68339f64c5f9.png)

![image](https://user-images.githubusercontent.com/2212681/174607477-edb5564b-5a9b-47be-a4fd-6e1d51c4b06b.png)

Either the version upgrade was necessary, or the bridge restart alone unblocked something.

**Comment by jm-clius** [comment]
Guessing it was the restart as the bridge has clearly been behaving erratically for a while:

![image](https://user-images.githubusercontent.com/68783915/174609099-acb21453-7c1b-447b-a95c-3503cd11a528.png)

Much more stable for `status.test`, though:

![image](https://user-images.githubusercontent.com/68783915/174609317-19f66f3a-4f93-4616-9859-6a0cd57eb7f7.png)

**Comment by jakubgs** [comment]
Good point, it appears the load looks fine for the past 30 days:

![image](https://user-images.githubusercontent.com/2212681/174609692-e52e294d-b300-4d2d-b6b8-bc8700b9d185.png)

But it looks like we had long periods of very low traffic:

![image](https://user-images.githubusercontent.com/2212681/174609773-9c11a148-b429-44ca-a3ce-c33224385bef.png)

**Comment by jakubgs** [comment]
But now it looks healthy, so I'm closing this:

![image](https://user-images.githubusercontent.com/2212681/174610212-e4234321-17e8-481b-92a5-b074f52a40e8.png)
